name: CD-FIX

on:
  workflow_run:
    workflows: ["CI-FIX"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Copy Files to EC2
        run: |
          pwd

      
      - name: Print Contents of Directory
        run: |
          ls -R $GITHUB_WORKSPACE

      - name: Check if CI was successful
        id: check_ci
        run: |
            if [ ${{ github.event.workflow_run.conclusion }} == "success" ]; then
              echo "CI was successful"
            else
              echo "CI was not successful"
              exit 1
            fi
