name: CD-FIX

on:
  workflow_run:
    workflows: ["CI-FIX"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
      - 28-fix-cicd


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Copy Files to EC2
        env:
            REPO_SOURCE_DIR: $GITHUB_WORKSPACE
            EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
            EC2_USER: ec2-user
            EC2_HOST: ec2-3-89-139-14.compute-1.amazonaws.com
            REPO_DEST_DIR: /home/ec2-user/github
        run: |                              
          scp -i $EC2_SSH_KEY -r $REPO_SOURCE_DIR $EC2_USER@$EC2_HOST:$REPO_DEST_DIR

      
      - name: Print Contents of Directory
        run: |
          ls -R $GITHUB_WORKSPACE

      - name: Check if CI was successful
        id: check_ci
        run: |
            if [ ${{ github.event.workflow_run.conclusion }} == "success" ]; then
              echo "CI was successful"
            else
              echo "CI was not successful"
              exit 1
            fi
