name: CD-FIX

on:
  workflow_run:
    workflows: ["CI-FIX"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
      - 28-fix-cicd


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Clone Repository
        run: |
          # Set the repository URL
          REPO_URL="https://github.com/maxmichalec/461-project-9-phase2/"
          
          # Set the destination directory (change to your desired path)
          mkdir github
          DEST_DIR="/github/"
          
          # Clone the repository
          git clone $REPO_URL $DEST_DIR
      
      - name: Print Contents of Directory
        run: |
          ls -R $GITHUB_WORKSPACE

      - name: Check if CI was successful
        id: check_ci
        run: |
            if [ ${{ github.event.workflow_run.conclusion }} == "success" ]; then
              echo "CI was successful"
            else
              echo "CI was not successful"
              exit 1
            fi
