name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull carolinecgilbert6/461-project-9-phase2:latest

    - name: Delete Old Docker Container
      run: sudo docker rm -f 461-project-9-phase2-container || true

    - name: Run Docker Container
      run: sudo docker run -d -p 9000:9000 --name 461-project-9-phase2-container carolinecgilbert6/461-project-9-phase2
      