name: CI-FIX

on:
  push:
    branches:
      - main
      - 28-fix-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd front-end
          npm install

      - name: Build Angular Application
        run: |
          cd front-end
          npm run build

      - name: Test Angular Application
        run: |
          cd front-end
          echo "add tests here"
