name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        npm install
        cd front-end && npm install

    - name: Build Application
      run: npm run build --prod

    - name: Print Repository Contents
      run: ls -R $GITHUB_WORKSPACE

    - name: Test the Application
      run: echo "Add testing for the application"

    - name: Login to Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build and Push Docker Image
      run: |
        cd front-end
        docker build -t carolinecgilbert6/461-project-9-phase2 .
        docker push carolinecgilbert6/461-project-9-phase2:latest

    - name: Print Docker Image Contents
      run: docker run carolinecgilbert6/461-project-9-phase2:latest ls -R /usr/share/nginx/html

