name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Application
      run: npm install && npm run build
    
    - name: Test the Application
      run: echo "Add testing for the application"

    - name: Login to Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: cd front-end && docker build -t carolinecgilbert6/461-project-9-phase2 .
      
    - name: Push to Dockerhub
      run: cd front-end && docker push carolinecgilbert6/461-project-9-phase2:latest