name: Build Angular Application

on:
  workflow_dispatch: {}
  push:
    branches:
      - main  
      - 3-github-actions-cicd

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x  # Adjust Node.js version as needed

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install project dependencies
        run: |
          cd front-end
          npm install

      - name: Build Angular Application
        run: |
          cd front-end
          ng build --prod
