name: Lint and Format

on:
    workflow_dispatch: {}
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint-and-format:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # Setup Node.js environment
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "18"

            # Cache dependencies
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # Install dependencies
            - name: Install Dependencies
              run: npm install && cd front-end && npm install && cd ..

            # Run ESLint
            - name: Run ESLint
              run: npx eslint . --ext .js,.jsx,.ts,.tsx

            # Run Prettier
            - name: Run Prettier Check
              run: npx prettier --check .
